export const itemData = [
    {
        "title":"Tax Laws Amendment (Tax Incentives for Innovation) Bill 2016",
        "chamber":"House of Representatives",
        "status":"Act","portfolio":"Treasury",
        "summary":"Amends the: Income Tax Assessment Act 1997, Income Tax Assessment Act 1936 and Taxation Administration Act 1953 to: create an early stage investor regime that provides tax incentives for qualifying investors through a non-refundable tax offset and capital gains tax exemption on innovation related investments; require early stage innovation companies to report on specific innovation related investments; and provide a mechanism for Innovation Australia to provide guidance about whether particular investment activities are ineligible activities; Income Tax Assessment Act 1997 to: provide non-refundable carry-forward tax offsets for limited partners in early stage venture capital limited partnerships (ESVCLP); provide for a capital gains tax exemption for fixed and unit trust beneficiaries of partners in ESVCLPs; and exclude small entities from eligible venture capital investment auditor requirements; Venture Capital Act 2002 to increase the maximum fund size for ESVCLPs to $200 million; Income Tax Assessment Act 1997 and Venture Capital Act 2002 to: remove the requirement that an ESVCLP divest an investment in an entity once the value of the entity’s assets exceeds $250 million; provide that an entity can invest in another entity and remain an eligible venture capital investment; and enable foreign venture capital funds of funds to hold more than 30 per cent of the committee capital of an ESVCLP and extend their access to capital gains tax and other income tax concessions in relation to eligible venture capital investments; and Income Tax Assessment Act 1936 and Taxation Administration Act 1953 to enable a managed investment trust to disregard its investment in, and through, an ESVCLP or venture capital limited partnership when determining if it is a trading trust."
    },{
        "title":"Tax Laws Amendment (Tax Incentives for Innovation) Bill 2016",
        "chamber":"House of Representatives",
        "status":"Act","portfolio":"Treasury",
        "summary":"Amends the: Income Tax Assessment Act 1997, Income Tax Assessment Act 1936 and Taxation Administration Act 1953 to: create an early stage investor regime that provides tax incentives for qualifying investors through a non-refundable tax offset and capital gains tax exemption on innovation related investments; require early stage innovation companies to report on specific innovation related investments; and provide a mechanism for Innovation Australia to provide guidance about whether particular investment activities are ineligible activities; Income Tax Assessment Act 1997 to: provide non-refundable carry-forward tax offsets for limited partners in early stage venture capital limited partnerships (ESVCLP); provide for a capital gains tax exemption for fixed and unit trust beneficiaries of partners in ESVCLPs; and exclude small entities from eligible venture capital investment auditor requirements; Venture Capital Act 2002 to increase the maximum fund size for ESVCLPs to $200 million; Income Tax Assessment Act 1997 and Venture Capital Act 2002 to: remove the requirement that an ESVCLP divest an investment in an entity once the value of the entity’s assets exceeds $250 million; provide that an entity can invest in another entity and remain an eligible venture capital investment; and enable foreign venture capital funds of funds to hold more than 30 per cent of the committee capital of an ESVCLP and extend their access to capital gains tax and other income tax concessions in relation to eligible venture capital investments; and Income Tax Assessment Act 1936 and Taxation Administration Act 1953 to enable a managed investment trust to disregard its investment in, and through, an ESVCLP or venture capital limited partnership when determining if it is a trading trust."
    },{
        "title":"Tax Laws Amendment (Tax Incentives for Innovation) Bill 2016",
        "chamber":"House of Representatives",
        "status":"Act","portfolio":"Treasury",
        "summary":"Amends the: Income Tax Assessment Act 1997, Income Tax Assessment Act 1936 and Taxation Administration Act 1953 to: create an early stage investor regime that provides tax incentives for qualifying investors through a non-refundable tax offset and capital gains tax exemption on innovation related investments; require early stage innovation companies to report on specific innovation related investments; and provide a mechanism for Innovation Australia to provide guidance about whether particular investment activities are ineligible activities; Income Tax Assessment Act 1997 to: provide non-refundable carry-forward tax offsets for limited partners in early stage venture capital limited partnerships (ESVCLP); provide for a capital gains tax exemption for fixed and unit trust beneficiaries of partners in ESVCLPs; and exclude small entities from eligible venture capital investment auditor requirements; Venture Capital Act 2002 to increase the maximum fund size for ESVCLPs to $200 million; Income Tax Assessment Act 1997 and Venture Capital Act 2002 to: remove the requirement that an ESVCLP divest an investment in an entity once the value of the entity’s assets exceeds $250 million; provide that an entity can invest in another entity and remain an eligible venture capital investment; and enable foreign venture capital funds of funds to hold more than 30 per cent of the committee capital of an ESVCLP and extend their access to capital gains tax and other income tax concessions in relation to eligible venture capital investments; and Income Tax Assessment Act 1936 and Taxation Administration Act 1953 to enable a managed investment trust to disregard its investment in, and through, an ESVCLP or venture capital limited partnership when determining if it is a trading trust."
    },{
        "title":"Tax Laws Amendment (Tax Incentives for Innovation) Bill 2016",
        "chamber":"House of Representatives",
        "status":"Act","portfolio":"Treasury",
        "summary":"Amends the: Income Tax Assessment Act 1997, Income Tax Assessment Act 1936 and Taxation Administration Act 1953 to: create an early stage investor regime that provides tax incentives for qualifying investors through a non-refundable tax offset and capital gains tax exemption on innovation related investments; require early stage innovation companies to report on specific innovation related investments; and provide a mechanism for Innovation Australia to provide guidance about whether particular investment activities are ineligible activities; Income Tax Assessment Act 1997 to: provide non-refundable carry-forward tax offsets for limited partners in early stage venture capital limited partnerships (ESVCLP); provide for a capital gains tax exemption for fixed and unit trust beneficiaries of partners in ESVCLPs; and exclude small entities from eligible venture capital investment auditor requirements; Venture Capital Act 2002 to increase the maximum fund size for ESVCLPs to $200 million; Income Tax Assessment Act 1997 and Venture Capital Act 2002 to: remove the requirement that an ESVCLP divest an investment in an entity once the value of the entity’s assets exceeds $250 million; provide that an entity can invest in another entity and remain an eligible venture capital investment; and enable foreign venture capital funds of funds to hold more than 30 per cent of the committee capital of an ESVCLP and extend their access to capital gains tax and other income tax concessions in relation to eligible venture capital investments; and Income Tax Assessment Act 1936 and Taxation Administration Act 1953 to enable a managed investment trust to disregard its investment in, and through, an ESVCLP or venture capital limited partnership when determining if it is a trading trust."
    },{
        "title":"Tax Laws Amendment (Tax Incentives for Innovation) Bill 2016",
        "chamber":"House of Representatives",
        "status":"Act","portfolio":"Treasury",
        "summary":"Amends the: Income Tax Assessment Act 1997, Income Tax Assessment Act 1936 and Taxation Administration Act 1953 to: create an early stage investor regime that provides tax incentives for qualifying investors through a non-refundable tax offset and capital gains tax exemption on innovation related investments; require early stage innovation companies to report on specific innovation related investments; and provide a mechanism for Innovation Australia to provide guidance about whether particular investment activities are ineligible activities; Income Tax Assessment Act 1997 to: provide non-refundable carry-forward tax offsets for limited partners in early stage venture capital limited partnerships (ESVCLP); provide for a capital gains tax exemption for fixed and unit trust beneficiaries of partners in ESVCLPs; and exclude small entities from eligible venture capital investment auditor requirements; Venture Capital Act 2002 to increase the maximum fund size for ESVCLPs to $200 million; Income Tax Assessment Act 1997 and Venture Capital Act 2002 to: remove the requirement that an ESVCLP divest an investment in an entity once the value of the entity’s assets exceeds $250 million; provide that an entity can invest in another entity and remain an eligible venture capital investment; and enable foreign venture capital funds of funds to hold more than 30 per cent of the committee capital of an ESVCLP and extend their access to capital gains tax and other income tax concessions in relation to eligible venture capital investments; and Income Tax Assessment Act 1936 and Taxation Administration Act 1953 to enable a managed investment trust to disregard its investment in, and through, an ESVCLP or venture capital limited partnership when determining if it is a trading trust."
    },{
        "title":"Tax Laws Amendment (Tax Incentives for Innovation) Bill 2016",
        "chamber":"House of Representatives",
        "status":"Act","portfolio":"Treasury",
        "summary":"Amends the: Income Tax Assessment Act 1997, Income Tax Assessment Act 1936 and Taxation Administration Act 1953 to: create an early stage investor regime that provides tax incentives for qualifying investors through a non-refundable tax offset and capital gains tax exemption on innovation related investments; require early stage innovation companies to report on specific innovation related investments; and provide a mechanism for Innovation Australia to provide guidance about whether particular investment activities are ineligible activities; Income Tax Assessment Act 1997 to: provide non-refundable carry-forward tax offsets for limited partners in early stage venture capital limited partnerships (ESVCLP); provide for a capital gains tax exemption for fixed and unit trust beneficiaries of partners in ESVCLPs; and exclude small entities from eligible venture capital investment auditor requirements; Venture Capital Act 2002 to increase the maximum fund size for ESVCLPs to $200 million; Income Tax Assessment Act 1997 and Venture Capital Act 2002 to: remove the requirement that an ESVCLP divest an investment in an entity once the value of the entity’s assets exceeds $250 million; provide that an entity can invest in another entity and remain an eligible venture capital investment; and enable foreign venture capital funds of funds to hold more than 30 per cent of the committee capital of an ESVCLP and extend their access to capital gains tax and other income tax concessions in relation to eligible venture capital investments; and Income Tax Assessment Act 1936 and Taxation Administration Act 1953 to enable a managed investment trust to disregard its investment in, and through, an ESVCLP or venture capital limited partnership when determining if it is a trading trust."
    },{
        "title":"Tax Laws Amendment (Tax Incentives for Innovation) Bill 2016",
        "chamber":"House of Representatives",
        "status":"Act","portfolio":"Treasury",
        "summary":"Amends the: Income Tax Assessment Act 1997, Income Tax Assessment Act 1936 and Taxation Administration Act 1953 to: create an early stage investor regime that provides tax incentives for qualifying investors through a non-refundable tax offset and capital gains tax exemption on innovation related investments; require early stage innovation companies to report on specific innovation related investments; and provide a mechanism for Innovation Australia to provide guidance about whether particular investment activities are ineligible activities; Income Tax Assessment Act 1997 to: provide non-refundable carry-forward tax offsets for limited partners in early stage venture capital limited partnerships (ESVCLP); provide for a capital gains tax exemption for fixed and unit trust beneficiaries of partners in ESVCLPs; and exclude small entities from eligible venture capital investment auditor requirements; Venture Capital Act 2002 to increase the maximum fund size for ESVCLPs to $200 million; Income Tax Assessment Act 1997 and Venture Capital Act 2002 to: remove the requirement that an ESVCLP divest an investment in an entity once the value of the entity’s assets exceeds $250 million; provide that an entity can invest in another entity and remain an eligible venture capital investment; and enable foreign venture capital funds of funds to hold more than 30 per cent of the committee capital of an ESVCLP and extend their access to capital gains tax and other income tax concessions in relation to eligible venture capital investments; and Income Tax Assessment Act 1936 and Taxation Administration Act 1953 to enable a managed investment trust to disregard its investment in, and through, an ESVCLP or venture capital limited partnership when determining if it is a trading trust."
    },{
        "title":"Tax Laws Amendment (Tax Incentives for Innovation) Bill 2016",
        "chamber":"House of Representatives",
        "status":"Act","portfolio":"Treasury",
        "summary":"Amends the: Income Tax Assessment Act 1997, Income Tax Assessment Act 1936 and Taxation Administration Act 1953 to: create an early stage investor regime that provides tax incentives for qualifying investors through a non-refundable tax offset and capital gains tax exemption on innovation related investments; require early stage innovation companies to report on specific innovation related investments; and provide a mechanism for Innovation Australia to provide guidance about whether particular investment activities are ineligible activities; Income Tax Assessment Act 1997 to: provide non-refundable carry-forward tax offsets for limited partners in early stage venture capital limited partnerships (ESVCLP); provide for a capital gains tax exemption for fixed and unit trust beneficiaries of partners in ESVCLPs; and exclude small entities from eligible venture capital investment auditor requirements; Venture Capital Act 2002 to increase the maximum fund size for ESVCLPs to $200 million; Income Tax Assessment Act 1997 and Venture Capital Act 2002 to: remove the requirement that an ESVCLP divest an investment in an entity once the value of the entity’s assets exceeds $250 million; provide that an entity can invest in another entity and remain an eligible venture capital investment; and enable foreign venture capital funds of funds to hold more than 30 per cent of the committee capital of an ESVCLP and extend their access to capital gains tax and other income tax concessions in relation to eligible venture capital investments; and Income Tax Assessment Act 1936 and Taxation Administration Act 1953 to enable a managed investment trust to disregard its investment in, and through, an ESVCLP or venture capital limited partnership when determining if it is a trading trust."
    },{
        "title":"Tax Laws Amendment (Tax Incentives for Innovation) Bill 2016",
        "chamber":"House of Representatives",
        "status":"Act","portfolio":"Treasury",
        "summary":"Amends the: Income Tax Assessment Act 1997, Income Tax Assessment Act 1936 and Taxation Administration Act 1953 to: create an early stage investor regime that provides tax incentives for qualifying investors through a non-refundable tax offset and capital gains tax exemption on innovation related investments; require early stage innovation companies to report on specific innovation related investments; and provide a mechanism for Innovation Australia to provide guidance about whether particular investment activities are ineligible activities; Income Tax Assessment Act 1997 to: provide non-refundable carry-forward tax offsets for limited partners in early stage venture capital limited partnerships (ESVCLP); provide for a capital gains tax exemption for fixed and unit trust beneficiaries of partners in ESVCLPs; and exclude small entities from eligible venture capital investment auditor requirements; Venture Capital Act 2002 to increase the maximum fund size for ESVCLPs to $200 million; Income Tax Assessment Act 1997 and Venture Capital Act 2002 to: remove the requirement that an ESVCLP divest an investment in an entity once the value of the entity’s assets exceeds $250 million; provide that an entity can invest in another entity and remain an eligible venture capital investment; and enable foreign venture capital funds of funds to hold more than 30 per cent of the committee capital of an ESVCLP and extend their access to capital gains tax and other income tax concessions in relation to eligible venture capital investments; and Income Tax Assessment Act 1936 and Taxation Administration Act 1953 to enable a managed investment trust to disregard its investment in, and through, an ESVCLP or venture capital limited partnership when determining if it is a trading trust."
    },{
        "title":"Tax Laws Amendment (Tax Incentives for Innovation) Bill 2016",
        "chamber":"House of Representatives",
        "status":"Act","portfolio":"Treasury",
        "summary":"Amends the: Income Tax Assessment Act 1997, Income Tax Assessment Act 1936 and Taxation Administration Act 1953 to: create an early stage investor regime that provides tax incentives for qualifying investors through a non-refundable tax offset and capital gains tax exemption on innovation related investments; require early stage innovation companies to report on specific innovation related investments; and provide a mechanism for Innovation Australia to provide guidance about whether particular investment activities are ineligible activities; Income Tax Assessment Act 1997 to: provide non-refundable carry-forward tax offsets for limited partners in early stage venture capital limited partnerships (ESVCLP); provide for a capital gains tax exemption for fixed and unit trust beneficiaries of partners in ESVCLPs; and exclude small entities from eligible venture capital investment auditor requirements; Venture Capital Act 2002 to increase the maximum fund size for ESVCLPs to $200 million; Income Tax Assessment Act 1997 and Venture Capital Act 2002 to: remove the requirement that an ESVCLP divest an investment in an entity once the value of the entity’s assets exceeds $250 million; provide that an entity can invest in another entity and remain an eligible venture capital investment; and enable foreign venture capital funds of funds to hold more than 30 per cent of the committee capital of an ESVCLP and extend their access to capital gains tax and other income tax concessions in relation to eligible venture capital investments; and Income Tax Assessment Act 1936 and Taxation Administration Act 1953 to enable a managed investment trust to disregard its investment in, and through, an ESVCLP or venture capital limited partnership when determining if it is a trading trust."
    },
]